/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface APMToVIPBridgeInterface extends Interface {
  getFunction(
    nameOrSignature: "ERC20_APM" | "VIP_TOKEN" | "bridge"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Bridged"): EventFragment;

  encodeFunctionData(functionFragment: "ERC20_APM", values?: undefined): string;
  encodeFunctionData(functionFragment: "VIP_TOKEN", values?: undefined): string;
  encodeFunctionData(functionFragment: "bridge", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "ERC20_APM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "VIP_TOKEN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
}

export namespace BridgedEvent {
  export type InputTuple = [
    senderERC20Address: AddressLike,
    receiverBEP20Address: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    senderERC20Address: string,
    receiverBEP20Address: string,
    amount: bigint
  ];
  export interface OutputObject {
    senderERC20Address: string;
    receiverBEP20Address: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface APMToVIPBridge extends BaseContract {
  connect(runner?: ContractRunner | null): APMToVIPBridge;
  waitForDeployment(): Promise<this>;

  interface: APMToVIPBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ERC20_APM: TypedContractMethod<[], [string], "view">;

  VIP_TOKEN: TypedContractMethod<[], [string], "view">;

  bridge: TypedContractMethod<
    [receiverBEP20Address: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ERC20_APM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VIP_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<
    [receiverBEP20Address: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Bridged"
  ): TypedContractEvent<
    BridgedEvent.InputTuple,
    BridgedEvent.OutputTuple,
    BridgedEvent.OutputObject
  >;

  filters: {
    "Bridged(address,address,uint256)": TypedContractEvent<
      BridgedEvent.InputTuple,
      BridgedEvent.OutputTuple,
      BridgedEvent.OutputObject
    >;
    Bridged: TypedContractEvent<
      BridgedEvent.InputTuple,
      BridgedEvent.OutputTuple,
      BridgedEvent.OutputObject
    >;
  };
}
